server:
  port: 8088

logging:
  level:
    org.springframework: INFO

spring:
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create
  messages:
    basename: messages
  security:
    user:
      name: username
      password: password
  h2:
    console:
      enabled: true
  datasource:
    url: jdbc:h2:mem:testdb

management:
  endpoints:
    web:
      exposure:
        include: "*"

