server:
  port: 8088

logging:
  level:
    org.springframework: INFO

spring:
  jpa:
    open-in-view: false
    generate-ddl: true
    show-sql: true
    hibernate:
      ddl-auto: update
  messages:
    basename: messages
  security:
    user:
      name: username
      password: password
  datasource:
    driverClassName: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://127.0.0.1:3306/test
    username: root
    password: root
  #redis cache
  cache:
    type: redis
  redis:
    host: localhost
    port: 6379

management:
  endpoints:
    web:
      exposure:
        include: "*"

